"""
data_loaders.py
===============
Loader for the WorldValuesBench dataset used in this paper.

Each question has a large pool of real human responses (mapped to [-1, 1])
and 500 synthetic responses generated by an LLM simulator.  The loader
returns:

    real_answers      : { question_id -> 1-D np.ndarray of real responses }
    syn_answers_dict  : { model_name  -> { question_id -> 1-D np.ndarray
                                            of synthetic responses } }
"""

from __future__ import annotations

import json
import pickle
from pathlib import Path

import numpy as np


# ---------------------------------------------------------------------------
# Data directory and dataset configuration
# ---------------------------------------------------------------------------
#
# All data lives inside the data/ folder next to this file.

DATA_DIR = Path(__file__).parent / "data"

DATASET_CONFIGS = {
    "worldvalue": {
        "response_range": 2.0,        # responses mapped to [-1, 1] (range = 2)
        "param_range":    (-1.0, 1.0),
        "n_max":          500,        # real-sample budget per question (~93k available)
        "k_max":          200,        # max synthetic samples (500 available)
    },
}


# ---------------------------------------------------------------------------
# WorldValuesBench loader
# ---------------------------------------------------------------------------

# Model name -> synthetic-answer pickle filename inside
# ``worldvalue/synthetic answers/clean/``.
WORLDVALUE_FILE_BY_MODEL = {
    "gpt4o":      "synthetic_answers_clean_gpt4o.pkl",
    "gpt-5-mini": "synthetic_answers_clean_gpt-5-mini.pkl",
    "llama-3.3":  "synthetic_answers_clean_llama-3.3.pkl",
    "Qwen3-235B": "synthetic_answers_clean_Qwen3-235B.pkl",
    "uniform":    "uniform_benchmark.pkl",
}


def load_worldvalue(
    models: list[str],
) -> tuple[dict[str, np.ndarray], dict[str, dict[str, np.ndarray]]]:
    """
    Load WorldValuesBench real and synthetic responses from
    ``data/worldvalue/``.

    Expected layout:
        data/worldvalue/retained_questions_235.json
        data/worldvalue/full_population_response_clean.pkl
        data/worldvalue/synthetic answers/clean/<file>.pkl   (one per model)

    Real responses come from the full population pool (~96K per question),
    which also serves as the ground truth for evaluating test coverage.  
    Each synthetic file holds 500 LLM responses per question (NaNs from unparseable
    generations are dropped).  Responses are already mapped to [-1, 1].

    Parameters
    ----------
    models : list of model names; each must be a key of
             ``WORLDVALUE_FILE_BY_MODEL``.

    Returns
    -------
    real_answers, all_syn_answers
    """
    wv_dir = DATA_DIR / "worldvalue"

    # 1. Retained question IDs (235 after preprocessing) --------------------
    q_file = wv_dir / "retained_questions_235.json"
    if not q_file.exists():
        raise FileNotFoundError(f"Question list not found: {q_file}")
    retained_questions: list[str] = json.loads(q_file.read_text())

    # 2. Real responses (full population pool) ------------------------------
    pop_file = wv_dir / "full_population_response_clean.pkl"
    if not pop_file.exists():
        raise FileNotFoundError(f"Population response file not found: {pop_file}")
    with open(pop_file, "rb") as f:
        full_pop = pickle.load(f)
    real_answers: dict[str, np.ndarray] = {
        q: np.asarray(full_pop[q], dtype=float)
        for q in retained_questions
        if q in full_pop
    }

    # 3. Synthetic responses per model --------------------------------------
    syn_dir = wv_dir / "synthetic answers" / "clean"
    all_syn_answers: dict[str, dict[str, np.ndarray]] = {}
    for model in models:
        if model not in WORLDVALUE_FILE_BY_MODEL:
            raise ValueError(
                f"Unknown WorldValuesBench model {model!r}. "
                f"Choose from {list(WORLDVALUE_FILE_BY_MODEL)}."
            )
        fpath = syn_dir / WORLDVALUE_FILE_BY_MODEL[model]
        if not fpath.exists():
            raise FileNotFoundError(f"Synthetic answer file not found: {fpath}")
        with open(fpath, "rb") as f:
            raw = pickle.load(f)
        syn_for_model: dict[str, np.ndarray] = {}
        for q_id in real_answers:
            if q_id not in raw:
                continue
            arr = np.asarray(raw[q_id], dtype=float)
            # Drop NaN entries (a few unparseable LLM responses).
            arr = arr[~np.isnan(arr)]
            syn_for_model[q_id] = arr
        all_syn_answers[model] = syn_for_model

    return real_answers, all_syn_answers
